# -*- coding: utf-8 -*-
"""Another copy of actualFastapi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGZWFhhRVDWvBf-EkCfCcMzRnHlzZQTk
"""

#Model.py will be use to create a table -->> sqlalchemy --->> ORM model(table) class ____(Base)
              #--- one to many relationship between em (cascade = "all, delete-orphan") --> deleting one table also removes its another table
#main.py ---> 4 steps: 1. Import 2. instating 3. loading 4. crud operation
#database.py -->> database engine --- SQLIte configuration
#schema.py --->> pydantic basemodel --->> whenever we see request body schema or response schema(baseModel)

# whenever you doing db.query operation next thing you need to write code for http 404 exception

#database.py
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base

DATABASE_URL = "sqlite:///./meditrack.db"           ########## main thing in this

engine = create_engine(DATABASE_URL, connect_args = {'check_same_thread':False})

SessionLocal = sessionmaker(bind = engine, autocommit = False, autoflush = False)

Base = declarative_base()1

def get_db():
  db = SessionLocal()
  try:
    yield db
  finally:
    db.close()

#models.py
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship

from database import Base  ##coming from database.py

class Clinic(Base):
  __tablename__ = "clinics"
  id = Column(Integer, primary_key = True, index = True)    #index =True -->. auto generated column
  name  = Column(String, nullable = False)          #a data field or database column is required and cannot be left empty or stored as null
  city = Column(String, nullable = False)

  appointments = relationship("Appointment", back_populates = "clinics", cascade = "all, delete-orphan")
   #variable name should be of another table name, relationship with another Class name, back_populates should be on own table
   ### cascade means deleting a clinic also lead a deletion of appointment


class Appointment(Base):
  __tablename__ = "appointments"
  id = Column(Integer, primary_key = True, index = True)
  patient_name = Column(String, nullable = False)
  status = Column(String, nullable = False)
  duration = Column(Integer, nullable = False)
  clinic_id = Column(Integer, ForeignKey("clinics.id"))

  clinics = relationship("Clinic", back_populates = "appointments")

#schemas.py
from typing import List
from pydantic import BaseModel, Field, ConfigDict

#go to error handling -- > for rules

class ClinicCreate(BaseModel):    # request does have constraint
  name : str = Field(..., min_length = 1)    # min_length means non emppty it will not be written directly as min_lenth, non empty will written
  city : str = Field(..., min_length = 1)

class ClinicOut(BaseModel): # response doesnt need any constraint
  id : int
  name : str
  city : str
  model_config = ConfigDict(from_attributes = True)  #whenever we write response model we need to write model_config
       # tells Pydantic to read data directly from regular class objects or database rows instead of just dictionaries

class ClinicWithAppointment(BaseModel):   #response model
  id : int
  name : str
  city : str
  aappointments : List[AppointmentOut]
  model_config = ConfigDict(from_attributes = True)

class AppointmentCreate(BaseModel):  #request model so there will be constraint
  patient_name : str = Field(..., min_length = 1)
  status : str = Field(..., min_length = 1)
  duration : int = Field(..., ge = 15)   # ge ---> >= ,,, gt --> greater than and vice versa

class AppointmentOut(BaseModel):  #response model
  id : int
  patient_name : str
  status : str
  duration : int
  model_config = ConfigDict(from_attributes = True)

#main.py
# fastapi -- > is basically use for communication and connection mainly/

from typing import Optional
from fastapi import FastAPI, Depends, HTTPException, Query, Response
from sqlalchemy.orm import Session
import uvicorn

#loading all the content from other files into this file - 3rd step
from database import engine, Base, get_db
from models import Clinic, Appointment
from schemas import ClinicCreate, ClinicOut, ClinicWithAppointment, AppointmentCreate, AppointmentOut

Base.metadata.create_all(bind = engine)
# used in SQLAlchemy to automatically create all the database tables defined by your ORM models
#If your models are defined in a separate file and your creation step is in another file- main.py,
               # Python does not read the model classes. If it doesn't read them, Base.metadata stays empty.
#Always explicitly import your model classes before calling create_all()

#Base: declarative base class that all your database models inherit from.
#metadata: registry object under the hood that collects all table schemas when you define your model classes.
#create_all(bind=engine): method that loops through the collected tables and executes the creation logic using your specific database connection (engine).

app = FastAPI()

@app.post('/clinics', response_model = ClinicOut, status_code = 201)    # in function signature they have provided output as ClinicOut thats why response_model = ClinicOut
def create_clinic(clinic : ClinicCreate, db : Session = Depends(get_db)): -> ClinicOut
  new_clinic = Clinic(
      name = clinic.name,
      city = clinic.city
  )
  db.add(new_clinic)
  db.commit()
  db.refresh(new_clinic)
  return new_clinic





@app.post('/clinics/{clinic_id}/appointments', response_model = AppointmentOut, status_code = 201)
def add_appointment(clinic_id : int, appointment : AppointmentCreate, db : Session = Depends(get_db)): -> AppointmentOut
  c = db.query(Clinic).filter(Clinic.id == clinic_id).first()
  #WHENEVER WE ARE USING DB.QUERY THEN ALWAYS CHECK FOR HTTPEXCEPTION ALWAYS
  if not c:
    raise HTTPException(status_code = 404, detail = "Clinic not found")

  new_appointment = Appointment(
      patient_name = appointment.patient_name,
      status = appointment.status,
      duration = appointment.duration,
  )
  db.add(new_appointment)
  db.commit()
  db.refresh(new_appointment)
  return new_appointment



@app.get("/clinic/{clinic_id}", response_model = ClinicWithAppointments)
def get_clinic(clinic_id : int, status: Optional[str] = None, sort: Optional[str] = None, db.Session = Depends(get_db))-> ClinicWithAppointments:
    c = db.query(Clinic).filter(Clinic.id == clinic_id).first()
    if c is None:
        raise HTTPException(status_code = 404, details = "Clinic not find")

    query = db.query(Appoinment).filter(Appointment.clinic_id == clinic_id)
    if status:
        query = query.filter(Appointment.status == status)

    if sort:
      if sort == "patient_name" :
        query = query.order_by(Appointment.patient_name.asc())
      if sort == "duration":
        query = query.order_by(Appointment.duration)

    appointments = query.all()

    return ClinicWithAppointments(
        id = c.id,
        name = c.name,
        city = c.city
        appointments = appointments
    )


@app.delete("/clinics/{clinic_id}", status_code = 204)
def delete_clinic(clinic_id : int, db : Session = Depends(get_db)):
  c = db.query(Clinic).filter(Clinic.id == clinic_id).first()
  if not c:
    raise HTTPExcception(status_code = 404, detail = "Clinic not found")

  db.delete(c)
  db.commit()
  return Response(status_code = 204)